import type { Menu } from '@/mocks/db/types'

export type MenuTreeItem = Menu

export const DEFAULT_MENU_TREE_DATA: Menu[] = [
  {
    id: 'menu_1',
    type: 'directory',
    path: '',
    title: 'Dashboard',
    icon: 'HOutline:HomeIcon',
    parentId: null,
    order: 0,
    status: 'active',
    createTime: '2025-12-12 14:00:12',
    updateTime: '2025-12-12 14:00:12',
    isBuiltIn: true,
    children: [
      {
        id: 'menu_12',
        type: 'menu',
        path: '/dashboard/home',
        title: '工作台',
        icon: 'HOutline:ComputerDesktopIcon',
        parentId: 'menu_1',
        order: 0,
        status: 'active',
        createTime: '2025-12-12 14:00:12',
        updateTime: '2025-12-12 14:00:12',
        isBuiltIn: true,
        children: [],
      },
      {
        id: 'menu_13',
        type: 'menu',
        path: '/dashboard/analysis',
        title: '分析页',
        icon: 'HOutline:ChartBarIcon',
        parentId: 'menu_1',
        order: 1,
        status: 'active',
        createTime: '2025-12-12 14:00:12',
        updateTime: '2025-12-12 14:00:12',
        isBuiltIn: true,
        children: [],
      },
      {
        id: 'menu_14',
        type: 'menu',
        path: '/dashboard/monitor',
        title: '监控页',
        icon: 'HOutline:EyeIcon',
        parentId: 'menu_1',
        order: 2,
        status: 'active',
        createTime: '2025-12-12 14:00:12',
        updateTime: '2025-12-12 14:00:12',
        isBuiltIn: true,
        children: [],
      },
    ],
  },
  {
    id: 'menu_2',
    type: 'directory',
    path: '',
    title: '系统管理',
    icon: 'HOutline:Cog6ToothIcon',
    parentId: null,
    order: 1,
    status: 'active',
    createTime: '2025-12-12 14:00:12',
    updateTime: '2025-12-12 14:00:12',
    isBuiltIn: true,
    children: [
      {
        id: 'menu_3',
        type: 'menu',
        path: '/system/user',
        title: '用户管理',
        icon: 'HOutline:UserGroupIcon',
        parentId: 'menu_2',
        order: 0,
        status: 'active',
        createTime: '2025-12-12 14:00:12',
        updateTime: '2025-12-12 14:00:12',
        isBuiltIn: true,
        children: [
          {
            id: 'menu_3_button_0',
            type: 'button',
            path: '',
            title: '添加用户',
            permission: 'user:add',
            parentId: 'menu_3',
            order: 0,
            status: 'active',
            createTime: '2025-12-12 14:00:12',
            updateTime: '2025-12-12 14:00:12',
            isBuiltIn: true,
            children: [],
          },
          {
            id: 'menu_3_button_1',
            type: 'button',
            path: '',
            title: '编辑用户',
            permission: 'user:edit',
            parentId: 'menu_3',
            order: 1,
            status: 'active',
            createTime: '2025-12-12 14:00:12',
            updateTime: '2025-12-12 14:00:12',
            isBuiltIn: true,
            children: [],
          },
          {
            id: 'menu_3_button_2',
            type: 'button',
            path: '',
            title: '删除用户',
            permission: 'user:delete',
            parentId: 'menu_3',
            order: 2,
            status: 'active',
            createTime: '2025-12-12 14:00:12',
            updateTime: '2025-12-12 14:00:12',
            isBuiltIn: true,
            children: [],
          },
          {
            id: 'menu_3_button_3',
            type: 'button',
            path: '',
            title: '查看用户',
            permission: 'user:view',
            parentId: 'menu_3',
            order: 3,
            status: 'active',
            createTime: '2025-12-12 14:00:12',
            updateTime: '2025-12-12 14:00:12',
            isBuiltIn: true,
            children: [],
          },
        ],
      },
      {
        id: 'menu_4',
        type: 'menu',
        path: '/system/role',
        title: '角色管理',
        icon: 'HOutline:IdentificationIcon',
        parentId: 'menu_2',
        order: 1,
        status: 'active',
        createTime: '2025-12-12 14:00:12',
        updateTime: '2025-12-12 14:00:12',
        isBuiltIn: true,
        children: [
          {
            id: 'menu_4_button_0',
            type: 'button',
            path: '',
            title: '添加角色',
            permission: 'role:add',
            parentId: 'menu_4',
            order: 0,
            status: 'active',
            createTime: '2025-12-12 14:00:12',
            updateTime: '2025-12-12 14:00:12',
            isBuiltIn: true,
            children: [],
          },
          {
            id: 'menu_4_button_1',
            type: 'button',
            path: '',
            title: '编辑角色',
            permission: 'role:edit',
            parentId: 'menu_4',
            order: 1,
            status: 'active',
            createTime: '2025-12-12 14:00:12',
            updateTime: '2025-12-12 14:00:12',
            isBuiltIn: true,
            children: [],
          },
          {
            id: 'menu_4_button_2',
            type: 'button',
            path: '',
            title: '删除角色',
            permission: 'role:delete',
            parentId: 'menu_4',
            order: 2,
            status: 'active',
            createTime: '2025-12-12 14:00:12',
            updateTime: '2025-12-12 14:00:12',
            isBuiltIn: true,
            children: [],
          },
          {
            id: 'menu_4_button_3',
            type: 'button',
            path: '',
            title: '查看角色',
            permission: 'role:view',
            parentId: 'menu_4',
            order: 3,
            status: 'active',
            createTime: '2025-12-12 14:00:12',
            updateTime: '2025-12-12 14:00:12',
            isBuiltIn: true,
            children: [],
          },
        ],
      },
      {
        id: 'menu_5',
        type: 'menu',
        path: '/system/menu',
        title: '菜单管理',
        icon: 'HOutline:ListBulletIcon',
        parentId: 'menu_2',
        order: 2,
        status: 'active',
        createTime: '2025-12-12 14:00:12',
        updateTime: '2025-12-12 14:00:12',
        isBuiltIn: true,
        children: [
          {
            id: 'menu_5_button_0',
            type: 'button',
            path: '',
            title: '添加菜单',
            permission: 'menu:add',
            parentId: 'menu_5',
            order: 0,
            status: 'active',
            createTime: '2025-12-12 14:00:12',
            updateTime: '2025-12-12 14:00:12',
            isBuiltIn: true,
            children: [],
          },
          {
            id: 'menu_5_button_1',
            type: 'button',
            path: '',
            title: '编辑菜单',
            permission: 'menu:edit',
            parentId: 'menu_5',
            order: 1,
            status: 'active',
            createTime: '2025-12-12 14:00:12',
            updateTime: '2025-12-12 14:00:12',
            isBuiltIn: true,
            children: [],
          },
          {
            id: 'menu_5_button_2',
            type: 'button',
            path: '',
            title: '删除菜单',
            permission: 'menu:delete',
            parentId: 'menu_5',
            order: 2,
            status: 'active',
            createTime: '2025-12-12 14:00:12',
            updateTime: '2025-12-12 14:00:12',
            isBuiltIn: true,
            children: [],
          },
          {
            id: 'menu_5_button_3',
            type: 'button',
            path: '',
            title: '查看菜单',
            permission: 'menu:view',
            parentId: 'menu_5',
            order: 3,
            status: 'active',
            createTime: '2025-12-12 14:00:12',
            updateTime: '2025-12-12 14:00:12',
            isBuiltIn: true,
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: 'menu_17',
    type: 'directory',
    path: '',
    title: '扩展组件',
    icon: 'HOutline:PuzzlePieceIcon',
    parentId: null,
    order: 2,
    status: 'active',
    createTime: '2025-12-12 14:00:12',
    updateTime: '2025-12-12 14:00:12',
    isBuiltIn: true,
    children: [
      {
        id: 'menu_18_1',
        type: 'menu',
        path: '/extended/tag',
        title: '标签',
        icon: 'HOutline:TicketIcon',
        parentId: 'menu_17',
        order: 0,
        status: 'active',
        createTime: '2025-12-12 14:00:12',
        updateTime: '2025-12-12 14:00:12',
        isBuiltIn: true,
        children: [],
      },
      {
        id: 'menu_18',
        type: 'menu',
        path: '/extended/button',
        title: '按钮',
        icon: 'HOutline:HandRaisedIcon',
        parentId: 'menu_17',
        order: 1,
        status: 'active',
        createTime: '2025-12-12 14:00:12',
        updateTime: '2025-12-12 14:00:12',
        isBuiltIn: true,
        children: [],
      },
      {
        id: 'menu_18_2',
        type: 'menu',
        path: '/extended/card',
        title: '卡片',
        icon: 'HOutline:RectangleStackIcon',
        parentId: 'menu_17',
        order: 2,
        status: 'active',
        createTime: '2025-12-12 14:00:12',
        updateTime: '2025-12-12 14:00:12',
        isBuiltIn: true,
        children: [],
      },
      {
        id: 'menu_19',
        type: 'menu',
        path: '/extended/dialog',
        title: '对话框',
        icon: 'HOutline:WindowIcon',
        parentId: 'menu_17',
        order: 3,
        status: 'active',
        createTime: '2025-12-12 14:00:12',
        updateTime: '2025-12-12 14:00:12',
        isBuiltIn: true,
        children: [],
      },
      {
        id: 'menu_20',
        type: 'menu',
        path: '/extended/iconSelector',
        title: '图标选择器',
        icon: 'HOutline:SwatchIcon',
        parentId: 'menu_17',
        order: 4,
        status: 'active',
        createTime: '2025-12-12 14:00:12',
        updateTime: '2025-12-12 14:00:12',
        isBuiltIn: true,
        children: [],
      },
      {
        id: 'menu_21',
        type: 'menu',
        path: '/extended/textEllipsis',
        title: '文本省略器',
        icon: 'HOutline:EllipsisHorizontalIcon',
        parentId: 'menu_17',
        order: 5,
        status: 'active',
        createTime: '2025-12-12 14:00:12',
        updateTime: '2025-12-12 14:00:12',
        isBuiltIn: true,
        children: [],
      },
      {
        id: 'menu_24',
        type: 'menu',
        path: '/extended/basePage',
        title: '基础Page组件',
        icon: 'HOutline:TableCellsIcon',
        parentId: 'menu_17',
        order: 6,
        status: 'active',
        createTime: '2025-12-12 14:00:12',
        updateTime: '2025-12-12 14:00:12',
        isBuiltIn: true,
        children: [],
      },
      {
        id: 'menu_22',
        type: 'menu',
        path: '/extended/hoverAnimation',
        title: 'Hover动画组件',
        icon: 'HOutline:CursorArrowRaysIcon',
        parentId: 'menu_17',
        order: 7,
        status: 'active',
        createTime: '2025-12-12 14:00:12',
        updateTime: '2025-12-12 14:00:12',
        isBuiltIn: true,
        children: [],
      },
      {
        id: 'menu_23',
        type: 'menu',
        path: '/extended/transitionAnimation',
        title: 'Transition内置动画',
        icon: 'HOutline:SparklesIcon',
        parentId: 'menu_17',
        order: 8,
        status: 'active',
        createTime: '2025-12-12 14:00:12',
        updateTime: '2025-12-12 14:00:12',
        isBuiltIn: true,
        children: [],
      },
    ],
  },
  {
    id: 'menu_15',
    type: 'directory',
    path: '',
    title: '功能演示',
    icon: 'HOutline:BeakerIcon',
    parentId: null,
    order: 3,
    status: 'active',
    createTime: '2025-12-12 14:00:12',
    updateTime: '2025-12-12 14:00:12',
    isBuiltIn: true,
    children: [
      {
        id: 'menu_16',
        type: 'menu',
        path: '/demo/vxeTable',
        title: 'VXE Table',
        icon: 'HOutline:TableCellsIcon',
        parentId: 'menu_15',
        order: 0,
        status: 'active',
        createTime: '2025-12-12 14:00:12',
        updateTime: '2025-12-12 14:00:12',
        isBuiltIn: true,
        children: [],
      },
      {
        id: 'menu_16_1',
        type: 'menu',
        path: '/demo/video',
        title: '视频播放器',
        icon: 'HOutline:VideoCameraIcon',
        parentId: 'menu_15',
        order: 1,
        status: 'active',
        createTime: '2025-12-12 14:00:12',
        updateTime: '2025-12-12 14:00:12',
        isBuiltIn: true,
        children: [],
      },
      {
        id: 'menu_16_2',
        type: 'menu',
        path: '/demo/konva',
        title: 'Konva',
        icon: 'HOutline:PhotoIcon',
        parentId: 'menu_15',
        order: 1,
        status: 'active',
        createTime: '2025-12-12 14:00:12',
        updateTime: '2025-12-12 14:00:12',
        isBuiltIn: true,
        children: [],
      },
    ],
  },
  {
    id: 'menu_9',
    type: 'directory',
    path: '',
    title: '异常页面',
    icon: 'HOutline:ExclamationTriangleIcon',
    parentId: null,
    order: 4,
    status: 'active',
    createTime: '2025-12-12 14:00:12',
    updateTime: '2025-12-12 14:00:12',
    isBuiltIn: true,
    children: [
      {
        id: 'menu_10',
        type: 'menu',
        path: '/exception/403',
        title: '403页面',
        icon: 'HOutline:NoSymbolIcon',
        parentId: 'menu_9',
        order: 0,
        status: 'active',
        createTime: '2025-12-12 14:00:12',
        updateTime: '2025-12-12 14:00:12',
        isBuiltIn: true,
        children: [],
      },
      {
        id: 'menu_11',
        type: 'menu',
        path: '/exception/404',
        title: '404页面',
        icon: 'HOutline:QuestionMarkCircleIcon',
        parentId: 'menu_9',
        order: 1,
        status: 'active',
        createTime: '2025-12-12 14:00:12',
        updateTime: '2025-12-12 14:00:12',
        isBuiltIn: true,
        children: [],
      },
    ],
  },
  {
    id: 'menu_6',
    type: 'directory',
    path: '',
    title: '一级菜单',
    icon: 'HOutline:FolderIcon',
    parentId: null,
    order: 5,
    status: 'active',
    createTime: '2025-12-12 14:00:12',
    updateTime: '2025-12-12 14:00:12',
    isBuiltIn: true,
    children: [
      {
        id: 'menu_7',
        type: 'directory',
        path: '',
        title: '二级菜单',
        icon: 'HOutline:FolderOpenIcon',
        parentId: 'menu_6',
        order: 0,
        status: 'active',
        createTime: '2025-12-12 14:00:12',
        updateTime: '2025-12-12 14:00:12',
        isBuiltIn: true,
        children: [
          {
            id: 'menu_8',
            type: 'menu',
            path: '/aaa/bbb/ccc',
            title: '三级菜单',
            icon: 'HOutline:DocumentTextIcon',
            parentId: 'menu_7',
            order: 0,
            status: 'active',
            createTime: '2025-12-12 14:00:12',
            updateTime: '2025-12-12 14:00:12',
            isBuiltIn: true,
            children: [],
          },
        ],
      },
    ],
  },
]

export type DefaultMenuTreeData = typeof DEFAULT_MENU_TREE_DATA
